#!/bin/bash
# eggd_additional_cnv_tasks 1.0.0
# Generated by dx-app-wizard.

# -e = exit on error; -x = output each line that is executed to log; -o pipefail = throw an error if there's an error in pipeline
set -e -x -o pipefail

main() {

    echo "Value of vcf: '$vcf'"
    echo "Value of length_only: '$length_only'"
    echo "Value of seg_only: '$seg_only'"

    # Download input vcf
    dx download "$vcf"


    mark-section "Installing packages"
    export PATH=$PATH:/home/dnanexus/.local/bin  # pip installs some packages here, add to path

    sudo -H python3 -m pip install --no-index --no-deps packages/*

    mark-section "Adding length to CNV"

    bcftools index $vcf_name
    python3 /home/dnanexus/add_length.py --vcf $vcf_name

    mark-section "Making seg visualisation file"

    python3 /home/dnanexus/make_seg.py --vcf $vcf_name

    mark-section "Uploading output"
    mkdir -p /home/dnanexus/out/seg_file
    mkdir -p /home/dnanexus/out/output_vcf

    outname=$(sed 's/.vcf\|.gz//g' <<< "$vcf_name")

    if [ "$length_only" == true ] && [ "$seg_only" == true ]; then
       dx-jobutil-report-error "Invalid option combination, please run as default. :)"
       exit 1

    elif [ "$length_only" == true ]; then
        mv "${outname}_length.vcf.gz" /home/dnanexus/out/output_vcf/

    elif [ "$seg_only" == true ]; then
        mv /home/dnanexus/*seg /home/dnanexus/out/seg_file/

    else
        mv "${outname}_length.vcf.gz" /home/dnanexus/out/output_vcf/
        mv /home/dnanexus/*seg /home/dnanexus/out/seg_file/

    fi

    # upload all outputs
    dx-upload-all-outputs --parallel

}
